name: CI/CD

on: push

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Unit Test
        run: dotnet test --no-build --verbosity normal
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username:  babicajakub 
          password:  i8HN8xn@m5JRdDbE
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: babicajakub/mywebapp:latest  # Please change the username here
      - name: Publish
        run: dotnet publish WebAPl/WebAPl.csproj -c Release -o website    
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: TodoApp/website/**
          if-no-files-found: error