name: CI/CD

on: push

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username:  babicajakub 
          password:  i8HN8xn@m5JRdDbE

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: babicajakub/mywebapp:latest  # Please change the username here